spring.application.name=scpcontainner

# ?????
server.servlet.context-path=/
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false

# MySQL ???????
spring.datasource.url=jdbc:mysql://localhost:3306/scpsystem?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari ?????
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=12
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# MyBatis ??
mybatis.configuration.map-underscore-to-camel-case=true

# ????
debug=false
logging.level.root=INFO
logging.level.com.zaxxer.hikari=INFO
logging.level.org.mybatis=INFO

